development:
  adapter: mysql2
  database: ov
  username: root
  password: a
  socket: /tmp/mysql.sock
  encoding: utf8
  timeout: 5000
  wait_timeout: 2147483
  pool: 5

test:
  adapter: mysql2
  database: ov_test
  username: root
  password: a
  socket: /tmp/mysql.sock
  encoding: utf8
  timeout: 5000
  wait_timeout: 2147483
  pool: 5
